### ISSUE TITLE
Show Git Branch with git-worktree Folders

### ISSUE THREAD

**Issue by MShuttle** [wisetime-io/vscode-branch-in-window-title#16]
The extension does not work for git-worktree branches.   Does not display the Extension label, nor the branch name. 

See attached screen-grab.   

![Screen Shot 2022-11-09 at 08 52 44](https://user-images.githubusercontent.com/144485/200693095-5bf6e2a2-924a-4965-946d-f8c0b79482b3.png)

**Comment by prwhite** [comment]
+1

**Comment by dslijepcevic** [comment]
Yes, basically you want the output of `git -C "${workspaceFolder}" branch --show-current` and in case this is empty (happens when HEAD is detached), then you probably want to display the output of `git -C "${workspaceFolder}" rev-parse --short HEAD`.

**Comment by AnrDaemon** [comment]
Should be fixed by #23 for good.

**Comment by vyshane** [comment]
We have released [v0.2.0](https://github.com/wisetime-io/vscode-branch-in-window-title/releases/tag/v0.2.0) which addresses this. Thank you for the implementation, @AnrDaemon.
