### ISSUE TITLE
Workspace settings keeps changing

### ISSUE THREAD

**Issue by Maxim-Filimonov** [wisetime-io/vscode-branch-in-window-title#6]
Hi,
I have noticed that the plugin keeps modifying workspace `settings.json` which my team is using to keep shared vscode settings. 
Is there a way to configure it to use my local `settings.json` instead of workspace settings.json?

**Comment by igumcheg** [comment]
Hi @Maxim-Filimonov, writing into local `settings.json` will update all the windows of vscode you have opened. Please also note that if you have two windows opened with different git branches used, it can cause infinite loop. Moreover vscode is not providing any tools to update local `settings.json` gracefully. 

I think for your case `git commit` hook can be used to remove lines updated by plugin in `settings.json`.
